import '@styles/reset.css'
import '@styles/variables.scss'
import '@styles/globals.scss'

import { ReactNode } from 'react'
import Container from '@layout/Container'
import Header from '@layout/Header'
import Provider from './Provider'
import styles from './styles.module.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='sv'>
      <body>
        <Provider>
          <Header />
          <main className={styles.main}>
            <Container>{children}</Container>
          </main>
        </Provider>
      </body>
    </html>
  )
}
